# spring config
spring:
  # hibernate config
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALAECT}
    hibernate:
      naming:
        physical-strategy: ${HIBERNATE_NAMING}

  # datasource config
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
